# Backpropagation algorithm to train a DNN with at least 2 hidden layers

In [6]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Sample data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])  # Reshape y to have the same shape as predictions

# Define the model architecture with 2 hidden layers
model = Sequential([
    Dense(4, activation='sigmoid', input_shape=(2,), use_bias=True),  # Hidden layer 1
    Dense(3, activation='sigmoid', use_bias=True),  # Hidden layer 2
    Dense(1, activation='sigmoid', use_bias=True)  # Output layer
])

In [7]:

# Print the weight matrices
print("Weight matrix for the first hidden layer:")
print(model.layers[0].get_weights()[0])  # Weight matrix for the first hidden layer

print("\nWeight matrix for the second hidden layer:")
print(model.layers[1].get_weights()[0])  # Weight matrix for the second hidden layer

print("\nWeight matrix for the output layer:")
print(model.layers[2].get_weights()[0])  # Weight matrix for the output layer

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Forward pass
print("\nForward pass:")
predictions = model.predict(X)


Weight matrix for the first hidden layer:
[[-0.78729033  0.006212   -0.5591965  -0.05758548]
 [ 0.32690096  0.526803    0.7465787  -0.39513445]]

Weight matrix for the second hidden layer:
[[ 0.84281516 -0.54980505 -0.915432  ]
 [ 0.7523217  -0.44807306 -0.04471183]
 [-0.3289116  -0.86866003 -0.35557324]
 [-0.7707951   0.5930033  -0.66535044]]

Weight matrix for the output layer:
[[-0.5371624 ]
 [ 0.8769561 ]
 [ 0.70627594]]

Forward pass:
1/1 [==============================] - 0s 99ms/step


In [8]:

# Backward pass
print("\nBackward pass (Gradients):")
with tf.GradientTape(persistent=True) as tape:
    tape.watch(model.trainable_variables)
    predictions = model(X)
    loss = tf.keras.losses.binary_crossentropy(y, predictions)

gradients = tape.gradient(loss, model.trainable_variables)
for grad, var in zip(gradients, model.trainable_variables):
    print(f"Gradient for {var.name}:\n{grad}\n")

# Clean up the resources used by the tape
del tape



Backward pass (Gradients):
Gradient for dense_9/kernel:0:
[[-0.01164253 -0.00270888 -0.00474305  0.00154413]
 [-0.00769512 -0.0041979  -0.00745365  0.00196611]]

Gradient for dense_9/bias:0:
[-0.02141561 -0.00925054 -0.01274958  0.00589681]

Gradient for dense_10/kernel:0:
[[-0.01054475  0.01809997  0.01202418]
 [-0.01419787  0.02259003  0.01634984]
 [-0.0131081   0.02209544  0.01545649]
 [-0.01163798  0.01767012  0.01218858]]

Gradient for dense_10/bias:0:
[-0.0256506   0.03973743  0.02814765]

Gradient for dense_11/kernel:0:
[[0.10601144]
 [0.0639274 ]
 [0.05544607]]

Gradient for dense_11/bias:0:
[0.18959236]

